feat: pulled image building and pushing to ecr_client
GetSimpl/cloudlift pull request #64
Opened 2020-10-20 04:31 UTC by pssaravanan

2020-12-01 12:54 UTC, shoan requested changes
The upload to ecr functionality is broken in this branch. Cloudlift can't find the local image.

2020-12-01 13:32 UTC, pssaravanan commented on cloudlift/__init__.py
> +def create_task_defn(name, environment, version, build_arg):
Made the changes

2020-12-01 13:33 UTC, pssaravanan commented on cloudlift/deployment/service_updater.py
> +            print(image_url)
Removed the print. It was used for debugging. missed to remove.

2020-12-01 13:50 UTC, pssaravanan commented on cloudlift/deployment/task_definition_service.py
> +class TaskDefinitionService:
Made the changes

2020-12-11 07:14 UTC, shoan approved these changes

2020-12-11 07:15 UTC, merged