Spot Instance and On-Demand support for deployment
GetSimpl/cloudlift pull request #75
Opened 2020-12-31 10:30 UTC by praveenraghav01

2021-01-11 07:12 UTC, shoan requested changes

2023-02-02 08:08 UTC, shoan requested changes
- Need alarm when spot capacity cannot be satisfied. This would be difference existing between desired count and actual
- Need to add `ECS_ENABLE_SPOT_INSTANCE_DRAINING` to ecs.config

2023-03-17 06:15 UTC, priyalatha-kr commented
Works as expected on the following criteria :
ecs_default_type is Ondemand and the Spot.deployment is set to false/True
ecs_default_type is Spot and the Spot.deployment is set to false/True
And when initiated interruption on the spot instance, new task is created before the draining of the old task/instance starts.

2023-03-21 09:01 UTC, shoan approved these changes

2023-03-21 09:36 UTC, merged